apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-api-config
  labels:
    app: my-app-api
data:
  app.yaml: |
    server:
      port: 8080
      timeout: 30s

    logging:
      level: info
      format: json

    metrics:
      enabled: true
      path: /metrics
