apiVersion: v1
kind: Service
metadata:
  name: my-app-api
  labels:
    app: my-app-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: my-app-api
