apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-app-api
  namespace: platform-governance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-app-api
subjects:
  - kind: ServiceAccount
    name: my-app-api
    namespace: platform-governance
