apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-app-api
  namespace: platform-governance
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
